//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiralama
    {
        public int kiraID { get; set; }
        public Nullable<int> oda { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<System.DateTime> girisTarih { get; set; }
        public Nullable<System.DateTime> cikisTarih { get; set; }
    
        public virtual musteri musteri { get; set; }
        public virtual oda oda1 { get; set; }
    }
}
