//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public musteri()
        {
            this.kiralama = new HashSet<kiralama>();
        }
    
        public int musID { get; set; }
        public string muskimlikno { get; set; }
        public string musAD { get; set; }
        public string musSoyad { get; set; }
        public Nullable<int> odaNum { get; set; }
        public Nullable<bool> durum { get; set; }
        public string musCinsiyet { get; set; }
        public string musMedeni { get; set; }
        public Nullable<int> musSayi { get; set; }
        public Nullable<int> musCocuk { get; set; }
        public string musAdres { get; set; }
        public Nullable<System.DateTime> musGirisTarihi { get; set; }
        public Nullable<System.DateTime> musCikisTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kiralama> kiralama { get; set; }
    }
}
